### ISSUE TITLE
Support travis-ci.com

### ISSUE THREAD

**Issue by SupinePandora43** [Lakkanna/the-travis-client#14]
token from travis-ci.com didn't work with this extension!

**Comment by Lakkanna** [comment]
add `travisClient.pro: true` and set api token, and restart the editor

**Comment by SupinePandora43** [comment]
will try it!

**Comment by SupinePandora43** [comment]
WORK!!!
![image](https://user-images.githubusercontent.com/36124472/61103377-cd628380-a482-11e9-9da9-90e234756021.png)
