### ISSUE TITLE
activation issue

### ISSUE THREAD

**Issue by virgilwashere** [Lakkanna/the-travis-client#8]
I'm still having no luck with the extension activating.

I'm running `code-insiders` and `remote-wsl` though.  Extension is installed in `WSL`.

Also the current repo has only `repositories.ts` in `src/helpers`.  My installed extension also includes a `Configuration.js`.  Before you refactored into `src/common/ProjectDetails.ts`

`package.json` says v0.0.7.

**Comment by Lakkanna** [comment]
It was having issue in .vscodeignore file, i was ignored nod_modules, because of that after publishing package not having node_modules, now it's fixed from 0.0.8 and 0.0.9. try by updating extension.

**Comment by Lakkanna** [comment]
this issue is not at fixed, working on that, extension working fine in my system but when i publish or package extension is not working. I'll fix this.

**Comment by Lakkanna** [comment]
This is issue is fixed in new version.

**Comment by Luxcium** [comment]
I am sad to inform you that I kind of having the same issue. My Travis API authentication token UxRWBLB-PRIVATE-mdcUCQ is not working ... to be sure I have tried both Set Comunity and Set Enterprise token

**Comment by Lakkanna** [comment]
Hi, please can you do me a favour? Set community token and restart vscode
and let me know is that working or not.
